# Generated by Django 5.1.4 on 2024-12-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('m3u8_url', models.URLField(null=True)),
                ('main_photo_url', models.URLField(null=True)),
                ('minutes', models.IntegerField(null=True)),
                ('is_published', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('login', models.EmailField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
